"""
Paper Search Agent (Agent 2) for the Literature Review Web Application.

Fans out to all four academic search sources (arXiv, Semantic Scholar, IEEE
Xplore, Google Scholar) concurrently for each supplied query, flattens and
deduplicates the results, and returns the top-*max_papers* papers ranked by
relevance score.

Concurrency model
-----------------
For each query the four search tools are gathered in parallel via
``asyncio.gather``.  All queries are themselves gathered in parallel, giving
an outer fan-out of ``len(queries) × 4`` concurrent coroutines.

Fault tolerance
---------------
Each individual tool already catches its own exceptions and returns ``[]``; any
remaining errors at the ``search_all_sources`` level are caught here so that a
failure in one source never aborts the entire search.  A WARNING is emitted for
every failed source; the agent continues as long as at least one source returns
results.
"""

from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING

from models.paper import Paper
from tools.arxiv_search import search_arxiv
from tools.ieee_search import search_ieee
from tools.scholar_search import search_google_scholar
from tools.semantic_scholar_search import search_semantic_scholar
from utils.deduplication import merge_paper_sources

if TYPE_CHECKING:
    from config.settings import Settings
    from services.cache_service import CacheService

logger = logging.getLogger(__name__)


async def run_paper_search(
    search_queries: list[str],
    max_papers: int,
    cache: "CacheService | None",
    settings: "Settings",
) -> list[Paper]:
    """Search all academic sources for the supplied queries and return ranked papers.

    The function caps input at the first 5 queries to avoid hitting per-source
    rate limits.  For each query all four search tools are called concurrently;
    all queries are also run concurrently.  Results are flattened, deduplicated
    via source-priority-aware merging, sorted by score descending, and trimmed
    to *max_papers*.

    Parameters
    ----------
    search_queries:
        List of query strings generated by the query-expansion agent.  Only the
        first 5 are used.
    max_papers:
        Target upper bound on the number of papers returned.  Each source is
        asked for ``max_papers // 4`` results; the final list is also capped at
        this value.
    cache:
        Optional :class:`~services.cache_service.CacheService` for read-through
        caching inside each search tool.
    settings:
        Application :class:`~config.settings.Settings` providing API keys for
        the authenticated sources.

    Returns
    -------
    list[Paper]
        Deduplicated papers sorted by ``score`` descending, truncated to at most
        *max_papers* entries.
    """
    # Limit to first 2 queries to reduce external API load and timeout risk.
    queries: list[str] = search_queries[:2]

    per_source_limit: int = max(1, max_papers // 4)

    # Semaphore caps concurrent source-level coroutines so the thread pool
    # executor is not flooded by blocking library calls.
    source_semaphore = asyncio.Semaphore(4)

    async def _guarded(coro) -> list[Paper] | BaseException:
        async with source_semaphore:
            try:
                return await coro
            except Exception as exc:  # noqa: BLE001
                return exc

    async def search_all_sources(query: str) -> list[Paper]:
        """Run all four search tools with concurrency capped by semaphore."""
        results: list[list[Paper] | BaseException] = await asyncio.gather(
            _guarded(search_arxiv(query, max_results=per_source_limit, cache=cache)),
            _guarded(search_semantic_scholar(
                query,
                max_results=per_source_limit,
                cache=cache,
                api_key=settings.SEMANTIC_SCHOLAR_API_KEY,
            )),
            _guarded(search_ieee(
                query,
                max_results=per_source_limit,
                cache=cache,
                api_key=settings.IEEE_API_KEY,
            )),
            _guarded(search_google_scholar(
                query,
                max_results=per_source_limit,
                cache=cache,
                serpapi_key=settings.SERPAPI_KEY,
            )),
        )

        source_names = ("arxiv", "semantic_scholar", "ieee", "google_scholar")
        papers: list[Paper] = []
        for source, result in zip(source_names, results):
            if isinstance(result, BaseException):
                logger.warning(
                    "run_paper_search: source '%s' failed for query=%r – %s",
                    source,
                    query,
                    result,
                )
            else:
                papers.extend(result)

        return papers

    # Process queries sequentially to avoid saturating the thread pool executor
    # with too many concurrent blocking calls at once.
    per_query_results: list[list[Paper] | BaseException] = []
    for q in queries:
        try:
            per_query_results.append(await search_all_sources(q))
        except Exception as exc:  # noqa: BLE001
            per_query_results.append(exc)

    # Flatten all results, logging any unexpected top-level failures.
    all_papers: list[Paper] = []
    for idx, result in enumerate(per_query_results):
        if isinstance(result, BaseException):
            logger.warning(
                "run_paper_search: query[%d]=%r raised an unexpected error – %s",
                idx,
                queries[idx],
                result,
            )
        else:
            all_papers.extend(result)

    total_before_dedup = len(all_papers)

    # Deduplicate using source-priority-aware merge.
    deduplicated: list[Paper] = merge_paper_sources(all_papers)
    total_after_dedup = len(deduplicated)

    # Sort by score descending and truncate to max_papers.
    deduplicated.sort(key=lambda p: p.score, reverse=True)
    final: list[Paper] = deduplicated[:max_papers]

    logger.info(
        "run_paper_search: papers before dedup=%d, after dedup=%d, final=%d",
        total_before_dedup,
        total_after_dedup,
        len(final),
    )

    return final


__all__ = ["run_paper_search"]
